module.id=${project.artifactId}
module.version=${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}
module.title=${project.name}
module.description=${project.description}
module.repo.version.min=26.2
